### ISSUE TITLE
[GH Actions] Commit 45815ad (update main.yml) may be breaking something

### ISSUE THREAD

**Issue by AfterNetwork** [smileycreations15/Smile.js#13]
The test CI wasn't able to run this.

**Comment by smileycreations15** [comment]
THE CI WAS BROKEN XD

**Comment by smileycreations15** [comment]
(the ci was broken the commit broke itself)

**Comment by smileycreations15** [comment]
Good report though :D

**Comment by smileycreations15** [comment]
@AfterNetwork Discord?

**Comment by smileycreations15** [comment]
you could paste it like this: `45815ad` and it will be a link like this: 45815ad
