### ISSUE TITLE
[GH Workflows] Put every commit into the CI workflow

### ISSUE THREAD

**Issue by AfterNetwork** [smileycreations15/Smile.js#14]
Checking for bugs.
Listed as GHW#1

**Comment by AfterNetwork** [comment]
oh #1

**Comment by smileycreations15** [comment]
NOT POSSIBLE :((((

**Comment by smileycreations15** [comment]
sorry that would crash github

**Comment by AfterNetwork** [comment]
then do it in GH desktop

**Comment by smileycreations15** [comment]
well

**Comment by smileycreations15** [comment]
not possible

**Comment by smileycreations15** [comment]
@AfterNetwork

**Comment by AfterNetwork** [comment]
just download the smile.js folder create the workflow first then import it via GH desktop (but it might take a long time)

**Comment by smileycreations15** [comment]
i cannot run through every commit

**Comment by AfterNetwork** [comment]
do it in an alt repo

**Comment by smileycreations15** [comment]
mine is a sloppy computer

**Comment by AfterNetwork** [comment]
to see if u can do it

**Comment by AfterNetwork** [comment]
wat os

**Comment by smileycreations15** [comment]
mac

**Comment by smileycreations15** [comment]
ram eaten by apps

**Comment by smileycreations15** [comment]
every new commit is now under CI

**Comment by smileycreations15** [comment]
try making a dummy commit (create a file called .gitkeep)

**Comment by smileycreations15** [comment]
@

**Comment by AfterNetwork** [comment]
i can't merge it

**Comment by smileycreations15** [comment]
ADMIN RESTRICTED

**Comment by smileycreations15** [comment]
smashes use ur admin privs
smashes merge branch

**Comment by smileycreations15** [comment]
success done
