### ISSUE TITLE
[FR191] Support windows by September 3rd

### ISSUE THREAD

**Issue by AfterNetwork** [smileycreations15/Smile.js#20]

**Comment by smileycreations15** [comment]
k

**Comment by AfterNetwork** [comment]
now it is for fall

**Comment by smileycreations15** [comment]
k

**Comment by AfterNetwork** [comment]
Do it today for the best. it will be included with FR191. FMR191 bug fixes releases today. (v1.2.1)

**Comment by AfterNetwork** [comment]
so the workflow fix and Node.JS merges will be included in (v1.2.1)

**Comment by AfterNetwork** [comment]
v1.2.5 is FR191

**Comment by smileycreations15** [comment]
NO BUGS IN WINDOWS just too lazy to set up checks

**Comment by smileycreations15** [comment]
@AfterNetwork

**Comment by AfterNetwork** [comment]
```FR191 = Fall Releases 2019 - Release 1
FRM191 - Minor Fall Releases 2019 - Release 1
WR191 - Winter Releases 2019 - Release 1```

**Comment by smileycreations15** [comment]
hey

**Comment by smileycreations15** [comment]
TYPESCRIPT FTW

**Comment by smileycreations15** [comment]
go to the discord-kinda chat thingy (github project)

**Comment by smileycreations15** [comment]
@AfterNetwork

**Comment by smileycreations15** [comment]
# WAT WILL BE OUR HIGHLIGHTS?

**Comment by AfterNetwork** [comment]
We could create a TyoeScript variant for smile.js

**Comment by smileycreations15** [comment]
OH YEA

**Comment by smileycreations15** [comment]
do you know typescriptdo you know typescript

**Comment by smileycreations15** [comment]
@AfterNetwork

**Comment by smileycreations15** [comment]
# WAT WILL BE OUR HIGHLIGHTS?

**Comment by smileycreations15** [comment]
@AfterNetwork

**Comment by AfterNetwork** [comment]
no i don't but u can make it.
Highlight: that more infinite storge thing

**Comment by smileycreations15** [comment]
(stop there it is not infinite but a lot like gigabytes)

**Comment by smileycreations15** [comment]
@AfterNetwork good tag

**Comment by AfterNetwork** [comment]
ka

**Comment by smileycreations15** [comment]
@AfterNetwork It seems like you didn't get GitHub actions

**Comment by AfterNetwork** [comment]
i did

**Comment by smileycreations15** [comment]
show me screenshot

**Comment by smileycreations15** [comment]
of the pageof the page

**Comment by AfterNetwork** [comment]
where can I upload

**Comment by smileycreations15** [comment]
click the  `Attach files by dragging & dropping, selecting or pasting them.` thing

**Comment by smileycreations15** [comment]
@AfterNetwork

**Comment by smileycreations15** [comment]
dont use a branch

**Comment by AfterNetwork** [comment]
I DON'T SEE IT``

**Comment by smileycreations15** [comment]
are you on mobile?

**Comment by smileycreations15** [comment]
click the text under the input

**Comment by smileycreations15** [comment]
Also you see that tab because it is enabled on the **repository owner's** account not yours

**Comment by AfterNetwork** [comment]
![stuff](https://user-images.githubusercontent.com/45772308/63402536-a3a95000-c390-11e9-81f1-24f094bde7c4.png)

**Comment by AfterNetwork** [comment]
![thing](https://user-images.githubusercontent.com/45772308/63402595-d3f0ee80-c390-11e9-920c-7e1f3f12c60f.png)

**Comment by AfterNetwork** [comment]
seee

**Comment by smileycreations15** [comment]
because it is enabled on my account. check any of your repos

**Comment by smileycreations15** [comment]
@AfterNetwork

**Comment by AfterNetwork** [comment]
nope don't see (because I have no appicable repos)

**Comment by smileycreations15** [comment]
there is no such thing as *applicable repos*.
If it is enabled on a user account it is enabled on all the repositories of the user.

**Comment by smileycreations15** [comment]
@AfterNetwork

**Comment by smileycreations15** [comment]
@AfterNetwork k?

**Comment by AfterNetwork** [comment]
> @AfterNetwork k?

how did u get accepted before me, I APPLIED FIRST

**Comment by smileycreations15** [comment]
@AfterNetwork Because I was more active on GitHub and a good coder.

**Comment by AfterNetwork** [comment]
> @AfterNetwork Because I was more active on GitHub and a good coder.

I am more active than u, good coding does not count (showing off)

**Comment by smileycreations15** [comment]
@AfterNetwork Actually no. Compare the charts.

**Comment by smileycreations15** [comment]
<img width="1440" alt="Screen Shot 2019-08-22 at 01 23 05" src="https://user-images.githubusercontent.com/45574030/63472642-6f5e8e00-c47b-11e9-8122-0ed513351138.png">

**Comment by smileycreations15** [comment]
I did make 2,922 contributions so I am more active

**Comment by smileycreations15** [comment]
@AfterNetwork

**Comment by smileycreations15** [comment]
@AfterNetwork Hi!

**Comment by AfterNetwork** [comment]
OKAY THIS IS OVER.

**Comment by AfterNetwork** [comment]
I'VE HAD IT WITH U.

**Comment by smileycreations15** [comment]
@AfterNetwork calm down

**Comment by AfterNetwork** [comment]
*please leave a messsage after the beep, beep!*

**Comment by smileycreations15** [comment]
@AfterNetwork accept the repo invite. i removed you bc i though you need to calm down now it is all ok

**Comment by smileycreations15** [comment]
here is the message:
```dockerfile
COPY . .
```

**Comment by smileycreations15** [comment]
@AfterNetwork 
me: sees /tmp/mysql.sock
also me: oh it is a socket
also me: *confusion*
also me: `curl --unix-socket /tmp/mysql.sock`
also me:
```js
var http = require('http');

http.createServer(function (req, res) {
  res.write('Hello World!\n');
  res.end();
}).listen("./test.sock");
```

**Comment by AfterNetwork** [comment]
give me the invite link

**Comment by AfterNetwork** [comment]
and admin access here

**Comment by smileycreations15** [comment]
i cannot give admin it is impossible

**Comment by smileycreations15** [comment]
@AfterNetwork https://github.com/smileycreations15/Smile.js/invitations

**Comment by AfterNetwork** [comment]
also, let's get on-topic with the idea

**Comment by smileycreations15** [comment]
@AfterNetwork idunno

**Comment by smileycreations15** [comment]
@AfterNetwork

**Comment by smileycreations15** [comment]
@AfterNetwork hey

**Comment by AfterNetwork** [comment]
closed whatever
