### ISSUE TITLE
[FR191] Update Discussion Issue

### ISSUE THREAD

**Issue by AfterNetwork** [smileycreations15/Smile.js#8]
Talk here

**Comment by smileycreations15** [comment]
Our highlights may be

**Comment by smileycreations15** [comment]
* Compression
* Browser Fingerprinting
* Website to image conversion
* IndexedDB

**Comment by smileycreations15** [comment]
@AfterNetwork

**Comment by AfterNetwork** [comment]
No browser fingerprinting. No tracking involved with the library. Compression can be a good highlight. Everything else is a bit off-semi-major.

**Comment by smileycreations15** [comment]
@AfterNetwork well it is not for tracking

**Comment by smileycreations15** [comment]
dont u get the purpose: like dupe-checking

**Comment by AfterNetwork** [comment]
> dont u get the purpose: like dupe-checking

So 1 highlight. Dupe-checking.

**Comment by smileycreations15** [comment]
it wont be used as much

**Comment by AfterNetwork** [comment]
We could do compression.

**Comment by smileycreations15** [comment]
yep

**Comment by smileycreations15** [comment]
Highlights:
# Compression
The compression module can be used to compress data transmitted over the internet to increase speeds.
## IndexedDB
Was `localStorage` too small? Use IndexedDB with our brand-new IndexedDB API to get access to more storage!
### Website to image conversion
Did your customers get confused when your site breaks and you have no way to get a screenshot of the website? Use this module to capture a screenshot & do anything with it.

**Comment by smileycreations15** [comment]
@AfterNetwork

**Comment by AfterNetwork** [comment]
Compression is a bit too big IndexedDB is best. (Website to image will not be used much)

**Comment by smileycreations15** [comment]
@AfterNetwork done

**Comment by AfterNetwork** [comment]
#7 needs to be done in the next 2 weeks

**Comment by smileycreations15** [comment]
@AfterNetwork what is the `new-UI` branch?
